CREATE TABLE IF NOT EXISTS Usuarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR ,
    email VARCHAR,
    senha VARCHAR,
    adicionado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    
)